# Generated by Django 4.0.3 on 2022-06-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_automobilevo_color_remove_automobilevo_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='saleperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salepersons', to='sales_rest.salesperson'),
        ),
    ]
