# Generated by Django 4.0.3 on 2022-06-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_vinvo_color_remove_vinvo_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryVinVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='VinVO',
            new_name='Vin',
        ),
    ]
