# Generated by Django 4.0.3 on 2022-06-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_inventoryvinvo_rename_vinvo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.DeleteModel(
            name='Vin',
        ),
    ]
